### ISSUE TITLE
memory explodes in data processing

### ISSUE THREAD

**Issue by nlpofwhat** [simonalexanderson/StyleGestures#14]
I found in motion/motion_data.py
the code "data[:,inds,:].reshape((nn, L, seqlen*n_feats))" consumes a lot of memory. When the code is called, my internal memory explodes.  My inernal memory is about 16G. Is there any solution for me other than extend extra memory because I dou't have enough money at all.

In addition ,I found the codes use too many "array.copy()" which I think it's unnecessary  and consumes a lot of memory. 

Thanks a lot!

**Comment by simonalexanderson** [comment]
Dear @firesoldier,
Thank you for the comment. We have not considered memory consumption too much, so any and all suggestions for improvements are much appreciated, as are pull requests.

Regarding the first issue, we prepare all conditioning (concatenated pose and control sequences) in advance during the initialization of the MotionData class. It should be straightforward to move this to the get_item() method, which would be much more memory efficient. Regarding redundant copy() statements, these are leftovers from early debugging efforts and should be removed. Thank you for pointing this out.

I hope this answers your questions and that your model training is successful!

**Comment by nlpofwhat** [comment]
thanks! I've solved the problem.

**Comment by stefan-kohnen** [comment]
Hi @nlpofwhat, 
I am interested in your code which loads the data more efficiently with regard to memory. Would you like to share this code with a pull request?
I'd appreciate it a lot! =)

**Comment by nlpofwhat** [comment]
> Hi @nlpofwhat,
> I am interested in your code which loads the data more efficiently with regard to memory. Would you like to share this code with a pull request?
> I'd appreciate it a lot! =)

please refer to : https://github.com/nlpofwhat/StyleGestures-WithSmallMemory

**Comment by nlpofwhat** [comment]
@stefan-kohnen @ghenter please refer to : https://github.com/nlpofwhat/StyleGestures-WithSmallMemory

**Comment by stefan-kohnen** [comment]
@nlpofwhat Thanks! :+1:

**Comment by cssddnnc9527** [comment]
@nlpofwhat  hi, thanks for your hard work in order to resolve the memory issue.But after use your code, I met the following error, any advice will be appreciated!

_log_dir:results/locomotion/log_20220802_1328
input_data: (13710, 80, 66)
test_data: (31, 100, 66)
train_data shape  (54440, 80, 66)
alidation_data shape  (100, 80, 66)
all_test_data shape  (31, 100, 66)
self.n_test %d 
 38
Traceback (most recent call last):
  File "/opt/pycharm/pycharm-community-2021.3.3/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm/pycharm-community-2021.3.3/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/media/mashaoming/t21/code/StyleGestures-master/train_moglow.py", line 45, in <module>
    x_channels, cond_channels = data.n_channels()
AttributeError: 'Locomotion' object has no attribute 'n_channels'

Process finished with exit code 1_
