### ISSUE TITLE
Trinity dataset

### ISSUE THREAD

**Issue by huliwenkidkid** [simonalexanderson/StyleGestures#2]
Hi,
Thanks for sharing the code. the data we got from Trinity is fbx for motion and wav for audio. Is there any chance to get the data pre-processing code for fbx file?
Thanks

**Comment by ghenter** [comment]
Hi huliwenkidkid,

Thank you for your interest in our work. We are looking to provide preprocessing guidelines and code in the near future, and have updated the main README to reflect this.

In brief, we think there are two important pre-processing steps for the motion. One is to convert the fbx files to bvh, like you mention. The other step is to correct some synchronisation issues in the raw TCD material, to make the motion align with the timings of the audio. For the fbx to bvh conversion, our original pipeline involved a certain amount of manual steps and also some code that we might not be at liberty to distribute ourselves. We have therefore developed a new version of our pipeline that does not use proprietary code. We intend to share our processing code as soon as we can, along with a file containing timing offsets between audio and motion for the synchronisation step. However, this might be a little while still due to the ongoing summer holidays.

If you are a participant in the [GENEA challenge](https://genea-workshop.github.io/2020/#gesture-generation-challenge), you will be provided pre-processed and audio-aligned motion data there.

**Comment by ghenter** [comment]
For the record, @simonalexanderson committed the data pre-processing code and guidelines discussed in this issue today.
