### ISSUE TITLE
Question about LSTM input shape 

### ISSUE THREAD

**Issue by TaeilJin** [simonalexanderson/StyleGestures#26]
Hi, Thank you for publishing the code, it is really helpful to me. 

I have a question about LSTM cell. 

When I debug the affine coupling layer, the input shape of each LSTM cell is a (batch size, 70, feature) during the training, and the input shape is a (batch size, 1, feature) during the generating sample data. 

In my knowledge, definition of LSTM input is a (batch size, sequence length, feature), and it means that we use 70 LSTM cells for training and we use a single cell for generating sample.

I suppose that LSTM input will be same both foward and reverse flow.

I am a beginner about Deep-learning framework, Could you tell me it is right or not which I understand?

Thank you

Taeil Jin

https://github.com/simonalexanderson/StyleGestures/blob/a7599355a7b6578dba96e5ec76cc7cfeedd272e8/glow/modules.py#L326

**Comment by ghenter** [comment]
Hi @TaeilJin,

Apologies for the late response. The last few weeks have been busy.

If I understand correctly, there's a simple reason for the shape difference you are wondering about. The dimension of interest here (dimension 1,  which measures 70 during training and 1 during synthesis) corresponds to time. During training, the entire input and output sequences are available to us, so we can easily run the LSTM (and the network) forwards over all 70 time steps in one go. This can be done without using any explicit for-loop over time, by appling the LSTM to the input sequence as normal.

Generation time is different. Here we do not know the output sequence, but must instead create it. However, because the MoGlow model is autoregressive, it takes the output of recent time steps as an _input_ to the flow when generating the next pose. This means that we must generate output poses one at a time, so that each new pose can be manually fed back in to the network to generate the next one. We also need [an explicit loop over time](https://github.com/simonalexanderson/StyleGestures/blob/a7599355a7b6578dba96e5ec76cc7cfeedd272e8/glow/generator.py#L65). This should explain why the input shape only contains 1 single time frame at any given point during synthesis.

**Comment by ghenter** [comment]
@TaeilJin Has your question in this issue been answered?
If so, I would recommend that you close the issue.

**Comment by ghenter** [comment]
Closing this since the question appears to have been answered.
