### ISSUE TITLE
Duration mismatch between input audio speech file and synthesized gesture

### ISSUE THREAD

**Issue by stefan-kohnen** [simonalexanderson/StyleGestures#27]
Hey everyone,
Thank you for this repository and sharing your code, it indeed produces great results.
After training your model, I've came across an issue concerning a mismatch between the length of the input audio file and the synthesized gesture sequence. The synthesized gesture sequence is 20 frames shorter than it should be, at least this is the result which I've got when I imported both the wav and bvh file into Blender and let them play alongside.

You should be able to reproduce this error with the following steps:
1. Use the method outlined in #17 for generating a dataset only consisting of `TestSeq001.wav` in `test_audio` folder and generating a gesture sequence based on this input
2. Compare the number of frames of the generated bvh file (`2331` frames) and the the file `TestSeq001.bvh` from the [zenodo repository with your submitted bvh files for the GENEA challenge] (https://zenodo.org/record/4088324) which has `2351` frames (`Cond_SC` should be correct, right?)
3. (Optional) Import both the resp. wav file and the synthesized bvh file into Blender (or similar) and play them back.

For me, about a second (=20 frames) of the animation was missing. I'd be happy if you have a look into this and tell me if you can reproduce this error, so I know if the problem is only on my end or not.

Thank you in advance!

Regards,
Stefan

**Comment by ghenter** [comment]
Hi there @stefan-kohnen,

Thank you for your question and for your kind words. Apologies for the late response on my part; we've had a busy few weeks.

I had a chat with @simonalexanderson, and I believe that the output sequences always end 20 frames before the input sequences because the model runs with 1 second (20 frames) of lookahead for the speech input. We found this one second of "future speech" to be necessary for the model to adequately be able to plan and prepare its gestures so that, e.g., strokes can be performed together with emphasis in the speech. The lookahead means that the output has to be 20 frames shorter than the input, since after that point only 19 or fewer frames of speech are available, leaving some of the inputs to the network undefined.

Simon tells me that he worked around this for the StyleGestures GENEA Challenge submission by manually padding the end of the input sequence with 20 frames of zeroes. A slightly more elegant solution might be to instead pad it with feature vectors that correspond to silence, i.e., the absence/end of speech. (Padding with silence is not the same as zero-padding, since the input data has been standardised such that the zero vector corresponds to the average of the speech feature vectors across the entire database, and the database contains speech as well as silence.)

I hope this answers your question!

**Comment by stefan-kohnen** [comment]
Hi @ghenter,
Yes, this makes very much sense to me. Thank you for explaining and giving me an idea for a workaround as well =)
