### ISSUE TITLE
This dataset link doesn't seem to work.

### ISSUE THREAD

**Issue by 110wuqu** [simonalexanderson/StyleGestures#40]
The link  https://kth.box.com/s/quh3rwwl2hedwo32cdg1kq7pff04fjdf .It showed that: This shared file or folder link has been removed or is unavailable to you when I click in.

**Comment by ghenter** [comment]
[The same question](https://github.com/simonalexanderson/StyleGestures/issues/1#issuecomment-1100654137) was previously asked in a comment to issue #1. As mentioned in [my response](https://github.com/simonalexanderson/StyleGestures/issues/1#issuecomment-1100654915), we are aware of the issue, which is due to the university stopping their use of the Box service, which has invalidated all our data-sharing links. I have spoken to @simonalexanderson, and he said he will update the readme.

In the meantime, here's the new link to the data in question, shared via OneDrive:
https://kth-my.sharepoint.com/:f:/g/personal/simonal_ug_kth_se/EuzCqSiScf5EvwWgZJ8EZ3wB24oPsKca9klzGzxzV-4N6g?e=BG1ELf

**Comment by 110wuqu** [comment]
Thank you for your prompt reply.

> [The same question](https://github.com/simonalexanderson/StyleGestures/issues/1#issuecomment-1100654137) was previously asked in a comment to issue #1. As mentioned in [my response](https://github.com/simonalexanderson/StyleGestures/issues/1#issuecomment-1100654915), we are aware of the issue, which is due to the university stopping their use of the Box service, which has invalidated all our data-sharing links. I have spoken to @simonalexanderson, and he said he will update the readme.
> 
> In the meantime, here's the new link to the data in question, shared via OneDrive: https://kth-my.sharepoint.com/:f:/g/personal/simonal_ug_kth_se/EuzCqSiScf5EvwWgZJ8EZ3wB24oPsKca9klzGzxzV-4N6g?e=BG1ELf
