### ISSUE TITLE
How to apply the output file(*.bvh) to 3D model file(*.3ds)

### ISSUE THREAD

**Issue by cssddnnc9527** [simonalexanderson/StyleGestures#44]
Dear author,

thanks for your great contribution.

Do you have any idea for applying the output file(*.bvh) to 3D model file(*.3ds) ?

Thanks in advance.

**Comment by ghenter** [comment]
Hello there @cssddnnc9527,

My expertise is the machine learning technology, rather than code or 3D graphics, so I am not the best person to answer this question. Autodesk has [an article on importing BVH (Biovision hierarchy) files into 3ds Max](https://knowledge.autodesk.com/support/3ds-max/learn-explore/caas/CloudHelp/cloudhelp/2021/ENU/3DSMax-Character-Animation/files/GUID-98DBA4D3-C199-41C7-B776-EE5668E613B9-htm.html). I'm fairly sure that your character needs to have the same skeleton structure as that used in the BVH file for this to work out of the box.

I hope this helps!

**Comment by ghenter** [comment]
@cssddnnc9527 Has your question in this issue been answered?
If so, I would recommend that you close the issue.

**Comment by ghenter** [comment]
Closing this since the question appears to have been answered.
