### ISSUE TITLE
The trained model posture shakes badly. What might be the cause? Is there any way to solve this problem?

### ISSUE THREAD

**Issue by a1223A** [simonalexanderson/StyleGestures#48]

**Comment by ghenter** [comment]
I have only seen these problems when things are not set up properly, so yes, it should be possible to solve this.

What data are you training on? Does the motion in the data you train on look good if you visualise it? Is there any phase wrapping, e.g., due to a poorly-chosen rest pose? The latter issue is not visible from the motion directly, but it can affect some machine-learning models a lot, as we touch upon in [a recent paper](https://dl.acm.org/doi/10.1145/3536221.3558058).

Also, training always gives bad and shaky results early on during training. How many updates did you train with, and at what batch size? How many GPUs are you using? Note that multi-GPU training is not supported and will lead to bad results, as [mentioned in our readme](https://github.com/simonalexanderson/StyleGestures#training).

**Comment by ghenter** [comment]
@a1223A Has your question been answered?
If so, I would recommend that you close the issue.
