### ISSUE TITLE
gesture synthesis dataset

### ISSUE THREAD

**Issue by stone100010** [simonalexanderson/StyleGestures#6]
How to get the data set of the gesture synthesis ?

**Comment by ghenter** [comment]
The gesture data is available at [http://trinityspeechgesture.scss.tcd.ie](http://trinityspeechgesture.scss.tcd.ie/). Since Trinity College Dublin requires interested parties to sign a license agreement and receive approval before gaining access the material, we cannot host it here.

Does this answer your question?
